### ISSUE TITLE
build requires nightly due to `exit_status_error`

### ISSUE THREAD

**Issue by xobs** [Qyriad/wdi-rs#1]
This library requires a nightly build, due to `build.rs` using `#[feature(exit_status_error)]`. This is part of issue https://github.com/rust-lang/rust/issues/84908.

It is possible to build this using a stable compiler by setting `RUSTC_BOOTSTRAP=1` or by using a nightly compiler.

The nightly requirement should be noted in the `README`, or this feature should be removed to allow it to be built on a stable compiler.

**Comment by esden** [comment]
Indeed, this does currently require nightly compiler. AFAIK this feature is on it's way to be stabilized so this requirement should disappear eventually. If I understood @Qyriad correctly it should be possible to work around this and not need nightly. But I am not sure about the details.

**Comment by Qyriad** [comment]
Correct. All the instances of `.exit_ok().expect("msg_here")` can be replaced with something like:
```rust
let success = cmd
    .status()
    .unwrap()
    .success();
if !success {
    panic!("msg_here");
}
```

Iirc at the time the Windows build required nightly anyway, but I *think* that's no longer the case.

**Comment by esden** [comment]
Thank you very much for the clarification @Qyriad :)

@xobs there are two ways we can approach it. We either change the code to remove the nightly requirement for now, but then we will probably not even notice when the feature becomes stable. Or we can leave it and just keep using the nightly for now. I did not make my mind up yet which solution is a better one. 

I could subscribe to the issue on rust-lang that you provided and monitor it. And keep a tracking issue for us to clean up the code eventually when the nightly feature becomes stable.

What are your suggestions and preferences?

**Comment by xobs** [comment]
I don't know when Rust will stabilize that feature. They tend to take a very long time, so it could be months. Meanwhile, it's a relatively simple patch, and I can confirm that https://github.com/blackmagic-debug/wdi-rs/pull/2 builds just fine on Rust 1.65.0.

Unless there's a reason to keep the nightly requirement for this feature -- for example ensuring that beginner developers don't build this themselves -- then I don't see the benefits of requiring nightly.

**Comment by esden** [comment]
Ok sounds good. I have reviewed, approved and merged #2. @xobs let me know if there are any more issues building on windows. Otherwise we can close this issue.

**Comment by dragonmux** [comment]
We're looking to tagging v0.1.0 so we can run a publication cycle to crates.io, as you've not posted anything further, may we assume that things have been working well for you and we can close this xobs?

**Comment by xobs** [comment]
Things have indeed been working well! Thanks for the discussion and the fixes.
